name: Webhook
on:
  push:
    branches: [ master ]

jobs:
  webhook:
    name: Webhook actions
    runs-on: ubuntu-latest
    steps:
    - uses: SenorGrande/actions@develop
      env:
        INPUT_WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }} 
